# Compilation dependencies
package 'curl'
package 'libbz2-dev'
package 'libncurses5-dev'
package 'libncursesw5-dev'
package 'libreadline-dev'
package 'libsqlite3-dev'
package 'libssl-dev'
package 'llvm'
package 'tk-dev'
package 'wget'
package 'xz-utils'
package 'zlib1g-dev'
