- name: Enable Touch ID PAM module
  become: true
  lineinfile:
    path: /etc/pam.d/sudo
    line: "auth       sufficient     pam_tid.so"
    insertbefore: "required"
    firstmatch: true
  when: ansible_facts['os_family'] == "Darwin"

- name: Install Homebrew
  shell: |
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash -
  args:
    creates: /opt/homebrew/bin/brew

- name: Update Homebrew
  command: /opt/homebrew/bin/brew update

- name: Install Homebrew formulae
  community.general.homebrew:
    name: "{{ item }}"
    force_formula: true
  loop: "{{ formulae }}"

- name: Install Homebrew cask
  community.general.homebrew_cask:
    name: "{{ item }}"
  loop: "{{ casks }}"

- name: Set macOS preferences
  include_tasks: tasks/macos-defaults.yml

- name: Enable locate launch daemon
  become: true
  command: launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist
