- name: Workstation
  hosts:
    - localhost

  vars:
    repos:
      - elliterate/dotfiles
      - elliterate/vim-config

  handlers:
    - name: Install repositories
      command: "{{ lookup('env', 'HOME') }}/src/github.com/{{ item }}/install.sh"
      loop: "{{ repos }}"

  tasks:
    - name: Enable Touch ID PAM module
      become: true
      lineinfile:
        path: /etc/pam.d/sudo
        line: "auth       sufficient     pam_tid.so"
        insertbefore: "required"
        firstmatch: true
      when: ansible_facts['os_family'] == "Darwin"

    - name: Create SSH directory
      file:
        path: "{{ lookup('env', 'HOME') }}/.ssh"
        state: directory
        mode: "0700"

    - name: Create SSH config file
      file:
        path: "{{ lookup('env', 'HOME') }}/.ssh/config"
        mode: "0600"

    - name: Create SSH config dropin directory
      file:
        path: "{{ lookup('env', 'HOME') }}/.ssh/config.d"
        state: directory
        mode: "0700"

    - name: Use dropin directory in SSH config
      lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.ssh/config"
        line: "Include config.d/*"

    - name: Install Homebrew bundle
      when: ansible_facts['os_family'] == "Darwin"
      block:
        - name: Install Homebrew
          shell: |
            curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash -
          args:
            creates: /opt/homebrew/bin/brew

        - name: Create Homebrew config directory
          file:
            path: "{{ lookup('env', 'HOME') }}/.homebrew"
            state: directory

        - name: Copy Homebrew bundle config
          copy:
            src: Brewfile
            dest: "{{ lookup('env', 'HOME') }}/.homebrew/Brewfile"
          register: brewfile

        - name: Install Homebrew bundle
          command: brew bundle --global
          when: brewfile.changed

    - name: Checkout repositories
      git:
        repo: "https://github.com/{{ item }}.git"
        dest: "{{ lookup('env', 'HOME') }}/src/github.com/{{ item }}"
      loop: "{{ repos }}"
      notify: Install repositories

    - name: Set macOS preferences
      script: set_macos_preferences.sh
      when: ansible_facts['os_family'] == "Darwin"
