- name: Workstation
  hosts:
    - localhost

  tasks:
    - include_tasks: tasks/macos.yml
      when: ansible_facts['os_family'] == "Darwin"

- name: Install repositories
  import_playbook: install-repositories.yml

- name: Configure SSH
  import_playbook: ssh-config.yml
